---
title: "ntpu-programming-for-data-science"
output: html_notebook
---

#setup
```{r}
library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
a <- 2
```

```{r}
`a`
```
```{r}
a2 <- 5L
```

```{r}
typeof(a2)
```

```{r}
class(a2)
```

```{r}
aVector<-c(5,6,7)
a2Vector<-c(5L,6L,7L)
class(aVector)
class(a2Vector)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```
```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}
class(studentMajors)
```
```{r}
levels(studentMajors)
```
levels顯示的類別名稱（categorical values）順序整數值即R真正儲存的內容:

法律系會存成1; 經濟系會存成2。

```{r}
studentMajors
```

```{r}
typeof(studentMajors)
```
```{r}
as.integer(studentMajors)
```
factor -> integer 
```{r}
number <- c(1.26,1.99,12)
number
```

```{r}
as.integer(number)
```

# Date and Time
```{r}
now("UTC")
```
```{r}
mdy("1,1,1999")
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
dtObjectVector
class(dtObjectVector)
typeof(dtObjectVector)
```
```{r}
as.integer(dtObjectVector)
```
```{r}
as.double(dtObjectVector)
```
```{r}
as.numeric(dtObjectVector)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
Sys.timezone()
```
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
class(twDateTime)
```

```{r}
twDateTime
as.double(twDateTime)
```
## Get date-time in a different time zone

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
```

```{r}
with_tz(twDateTime, "UTC")
```

```{r}
with_tz(LisbonDateTime, "UTC")
```

```{r}
ymd("2018-09-11")
```

```{r}
mdy("Mar 3, 2019")
```
# Operation on Vectors
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```
```{r}
a+b
a*b
round(a/b, digits = 3)
 a^2
a%%2
```

```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
class(aL)
```

```{r}
a+aL
class(a+aL)
aL+bL
class(aL+bL)
```
```{r}
4+a
```

```{r}
twDateTime
twDateTime + 1
twDateTime + 86400
```
```{r}
dayDiff <- ymd("2019-08-11")- ymd("2000-01-01")
dayDiff
class(dayDiff)
```

因為2000年是閏年 所以 1-year period and 1-year duration 不同
```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1) #period
startingDate + dyears(1) #duration
```

```{r}
startingDate + 365
```


```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
class(endingDate - startingDate)

```

## realational operator

```{r}
x <- 5
y <- 7

x==y
x!=y
```

```{r}
x2 <- c(1,5,10)
y2 <- c(-1,5,20)

x2==y2
x2[[2]]==y2[[2]]
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3[1] == y3[1]
x3[2] != y3[2]
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
y4 %in% x4
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
is.na(x2)
sum(x2)
sum(x2, na.rm = T)
x2 + 1
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```

```{r}
as.factor(currency) -> currency
levels(currency)
```

```{r}
length(levels(currency))
```

```{r}
sum(currency == "日圓JPY/USD")
```

# logical operaor

```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```

```{r}
(x5 %in% greatTaipei) & (y5=="女")
```
```{r}
(x5 %in% greatTaipei) | (y5=="女")
which((x5 %in% greatTaipei) | (y5 ==""))
```


either or （排除同時滿足）
```{r}
xor(x5 %in% greatTaipei, y5=="女")
```
```{r}
y5
(y5 == "女")
which(y5=="女")
```
###practice1
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```

```{r}
as.Date(date) -> date

sum( date >= "1980-08-01")

sum(currency == "歐元USD/EUR")

sum(is.na(exchangeRate))

sum(!is.na(exchangeRate) & currency == "歐元USD/EUR")

```
###practice2
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```

```{r}
levels(as.factor(major)) 
```


```{r}
sum(major == "經濟學系" )

sum(studentID == "5bdS6977b")

sum(studentID == "5bdS6977b" & grade >= 60)

sum(major == "經濟學系" &courseType =="選")

sum(major == "經濟學系"& courseType == "必" & grade < 60, na.rm = T)-> Econfail

Econfail

sum(major == "經濟學系"& courseType == "必")
sum(major == "經濟學系"& courseType == "必", na.rm = T)

Econfail / sum(major == "經濟學系"& courseType == "必", na.rm = T) * 100



```
# operation on strings
```{r}
library(stringr)
```

##subset

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
```

```{r}
str_subset(course,"經濟學")

str_detect(course,"經濟學")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')

str_sub(studentID,2,4)
```

##join

```{r}
month <- c("3","4","2")
day <- c("11","5","7")

char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)

str_c(month,"月",day, "日")


str_c(month,"月",day, "日", sep =" ", collapse = T)
```

##split
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

```{r}
dates
str_replace(dates,"-","月")
```

```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```
##practice

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
username
reponame
```

```{r}
HTTP <- "https://github.com/"

UserRepo <-str_c(username,reponame, sep = "/")

HTTPs <- str_c(HTTP, UserRepo)

HTTPs

str_c("https://github.com/",username, reponame, sep = "/")
```

```{r}
"https://github.com/tpemartin/107-2-inclass-practice" -> model

str_replace(model, "tpemartin", username)-> step1
str_replace(answer, "107-2-inclass-practice", reponame)->answer

answer
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```

```{r}
Year <- str_sub(birthday,1,4)
Month <- str_sub(birthday, 5,6)
Date <- str_sub(birthday, 7, 8)

birthdayAD <-str_c("西元",Year, "年", Month, "月", Date, "日")
```


```{r}
民國年月<-c("099/01","099/02","099/03")

CYear <- str_sub(民國年月,1,3)

CMonth <- str_sub(民國年月, 5,6)

CMonth

as.numeric(CYear)-> CYear

CYear + 1911 -> CYear

str_c(CYear,CMonth, sep = "/")-> ADYear

```
#Vector

```{r}
a<-c(1:3)
typeof(a)
a
```

name = value 命名
```{r}
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(aWithNames)
aWithNames
```

```{r}
b1 <- list("a", "b", c(1:10))
b1
typeof(b1)
class(b1)

```

```{r}
b2<-list(
  第一個="a",
  第二個="b",
  第三個=c(1:10))
b2
```

```{r}
b2[["第一個"]]
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[["greenBox"]]
plasticContainer[[1]]
plasticContainer$greenBox
plasticContainer[1]
```

```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]

plasticContainer[["greenBox"]][[1]]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```

```{r}
成績單[[1]]
```

```{r}
studentRecord[[4]][[3]]
```

