---
title: "R practice and exam"
output: html_notebook
---

https://garylkl.shinyapps.io/Chapter4/#section-practice-2

#practice
##2
```{r}
library(readr)
library(stringr)
library(lubridate)
TyphoonData <- read_csv("https://raw.githubusercontent.com/GaryLKL/course-programming-for-ds-Quiz/master/TyphoonData.csv", col_types = cols(.default = col_character()))
Year <- TyphoonData$年份
```

```{r}
as.integer(Year)-> Year
Year - 1911 ->Year
as.character(Year)-> Year
str_c("民國",Year, "年")-> Year
```


```{r}
library(readr)
library(stringr)
TyphoonData <- read_csv("https://raw.githubusercontent.com/GaryLKL/course-programming-for-ds-Quiz/master/TyphoonData.csv", col_types = cols(.default = col_character()))
Time <- TyphoonData$發布警報時間
```

```{r}
str_sub(Time,6,7)-> TyphoonMonth
table(TyphoonMonth)
```


https://via.hypothes.is/https://tpemartin.github.io/course-107-2-learning-progress/past_homework_exam.html
#個人學習歷程
##homework1
```{r}
library(lubridate); library(stringr)

```

```{r}
major <- c("經濟系","法律系","社會系","經濟系")
grade <- c(50,60,92,88)
```

```{r}
fromEcon <- major == "經濟系"
fromEcon
```

```{r}
meanEcon<- sum(fromEcon*grade)/sum(fromEcon)
```

```{r}
library(readr)
podcastcompetition3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
submitTime <- podcastcompetition3$Timestamp
head(submitTime)
```
```{r}
submitTime<- mdy_hms(submitTime)
```

```{r}
tw_time<- with_tz(submitTime, tzone = "Asia/Taipei")
```

```{r}
nightOwl<- 1>= hour(tw_time) & hour(tw_time)<= 6

```

```{r}
nightOwlVoteShare<- sum(nightOwl)/ length(tw_time)

```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
studentID <- transcriptDataFinal$學號
schoolYear <- transcriptDataFinal$學年
grade <- transcriptDataFinal$學期成績
credit <- transcriptDataFinal$學分數
```

```{r}
GradePass <- grade >= 60
GradeFail <- grade <60
earnedCredit<- credit* GradePass
```

```{r}
SelectedStu<- studentID == "046S6f645" & schoolYear == 100
```

```{r}
credit100ChosenStudent<- sum(credit[SelectedStu])
```


```{r}
earnedCredit100ChosenStudent<- sum(earnedCredit[SelectedStu])

```

```{r}
SelectedStu1<- studentID == "046S6f645" & schoolYear == 100 & grade > 0

sum(
  credit[SelectedStu1]*grade[SelectedStu1]/sum(credit[SelectedStu1])
  )
  

```

##homework2
```{r}
library(lubridate); library(stringr); library(dplyr)
```

```{r}
obj11 <- c(
  小明=55,
  小新=88,
  Eric=73
)
names(obj11) 
```


```{r}
names(obj11) <- c("Ming","Shawn","Eric") ### <- 號右側是character vector, 其長度要和names(obj11)相同。
names(obj11)
obj11
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )
```

```{r}
names(studentRecord)[4] <- "平均成績"
studentRecord

```

```{r}
names(studentRecord[[4]]) <- c("一","二","三","四")
studentRecord
```
```{r}
library(httr)
commitCheck <- content(GET("https://api.github.com/repos/rstudio/rstudio/commits"))
```

```{r}
commit8Date <- commitCheck[[8]][["commit"]][["committer"]][["date"]]
commit8Date
```
```{r}
commit8TWDate<- with_tz(ymd_hms(commit8Date), tzone = "Asia/Taipei")
commit8TWDate
```
```{r}
length(commitCheck)

names(commitCheck)<- str_c("commit", c(1:30))
names(commitCheck)
```

```{r}
library(purrr)
map(commitCheck,~.[[3]][[2]][[3]][[1]]) -> allCommitDatesList
```

```{r}
unlist(allCommitDatesList)-> allCommitDates
allCommitDates
```

```{r}
library(lubridate)
ymd_hms(allCommitDates)->allCommitDates
with_tz(allCommitDates, tzone = "Asia/Taipei")->allCommitDatesTW
```

```{r}
hour(allCommitDatesTW)-> Hour
minute(allCommitDatesTW)-> Minute
hh.mm<- Hour+Minute/60
logicWithinTimeFrame<- hh.mm >= 4.5 & hh.mm <= 6.5
```

```{r}
library(readr)
transcriptData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
variable.names(transcriptData)-> variableNames

transcriptData$學系 == "經濟學系"-> logicFromEcon

```

```{r}
transcriptData[c(1,7,8)]-> transcriptPartialData
```

```{r}
transcriptPartialDataEcon <- list(
  學號=transcriptPartialData$學號[logicFromEcon],
  學分數=transcriptPartialData$學分數[logicFromEcon],
  "必選修類別（必∕選∕通）"=transcriptPartialData$`必選修類別（必∕選∕通）`[logicFromEcon]
)

transcriptPartialDataEcon
```

##homework3
```{r}
library(lubridate); library(stringr); library(purrr); library(readr)

```

```{r}
library(readr)
finStatement <- read_csv("http://mopsfin.twse.com.tw/opendata/t187ap06_O_ci.csv")
```

```{r}
finStatement$`營業利益（損失）` < 0 -> LogicLoss

loss1Companies <- finStatement$公司名稱[LogicLoss]

```

```{r}
finStatement$`基本每股盈餘（元）` < 0 -> LogicEPS

loss2Companies <- finStatement$公司名稱[LogicEPS]


```

```{r}
LogicLoss & !LogicEPS | !LogicLoss & LogicEPS -> Logic3
finStatement$公司名稱[Logic3]
```

```{r}
xor(LogicEPS,LogicLoss) -> logiOnly1Loss
finStatement$公司名稱[logiOnly1Loss] -> only1LossCompanies
only1LossCompanies
```
```{r}
finStatement[logiOnly1Loss,]->subsample
```

```{r}
library(httr)
exhibitionList <- content(GET("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=6"))
```

```{r}
str(exhibitionList[[1]])
```

```{r}
length(exhibitionList)-> numExhibitionList

```

```{r}
df_oneShow <- data.frame(
  title = exhibitionList[[1]][["title"]],
  time = exhibitionList[[1]][["showInfo"]][[1]][["time"]],
  location = exhibitionList[[1]][["showInfo"]][[1]][["location"]],
  locationName =exhibitionList[[1]][["showInfo"]][[1]][["locationName"]],
  price = exhibitionList[[1]][["showInfo"]][[1]][["price"]],
  endTime =exhibitionList[[1]][["showInfo"]][[1]][["endTime"]],
  sourceWebName = exhibitionList[[1]][["sourceWebName"]],
  stringsAsFactors = F
)
```

```{r}
df_oneShow
```


#midterm1
```{r}
library(lubridate); library(stringr); library(dplyr); library(readr); library(purrr)

```

